### ISSUE TITLE
ArgumentOutOfRangeException in DateTimeChartRangeControlClient

### ISSUE THREAD

**Issue by lethek** [awaescher/Fusion#16]
While Fusion++ was attempting to parse the logs recorded for an IIS-hosted web-app, it threw this uncaught exception and did not proceed any further:

```
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime. (Parameter 'value')
   at System.DateTime.AddTicks(Int64 value)
   at System.DateTime.Add(Double value, Int32 scale)
   at System.DateTime.AddMilliseconds(Double value)
   at DevExpress.XtraEditors.DateTimeChartRangeControlClient.NativeValue(Double value)
   at DevExpress.XtraEditors.ChartRangeControlClientBase.GetArgumentRange()
   at DevExpress.XtraEditors.ChartRangeControlClientRange.UpdateWithDataArgumentRange()
   at DevExpress.XtraEditors.ChartRangeControlClientBase.InteractionUpdated()
   at DevExpress.XtraEditors.ChartRangeControlClientBase.CoreClientDelegate.DevExpress.ChartRangeControlClient.Core.IChartCoreClientDelegate.InteractionUpdated()
   at DevExpress.ChartRangeControlClient.Core.ChartCoreClient.DataProviderDataChanged(IClientDataProvider provider)
   at DevExpress.XtraEditors.ChartRangeControlClientDataProvider.InternalClientDataProvider.RaiseDataChanged()
   at DevExpress.XtraEditors.ChartRangeControlClientDataProvider.BindingDelegateBindingChanged()
   at DevExpress.XtraEditors.ChartRangeControlClientDataProvider.InternalBindingSourceDelegate.DevExpress.ChartRangeControlClient.Core.IBindingSourceDelegate.BindingChanged()
   at DevExpress.ChartRangeControlClient.Core.BindingSource.RaiseBindingChanged()
   at DevExpress.ChartRangeControlClient.Core.BindingSource.set_ItemsSource(Object value)
   at DevExpress.XtraEditors.ChartRangeControlClientDataProvider.ApplyRealDataSettings()
   at DevExpress.XtraEditors.ChartRangeControlClientDataProvider.UpdateBindingSource(Boolean invalidateRangeControl)
   at FusionPlusPlus.Forms.MainForm.LoadLogsAsync(ILogStore logStore)
   at FusionPlusPlus.Forms.MainForm.LoadLogsAsync(String path)
   at FusionPlusPlus.Forms.MainForm.ImportFromDirectoryAsync(String directory)
   at FusionPlusPlus.Forms.MainForm.<>c__DisplayClass35_1.<<PopulateLastSessions>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
```

The full error message reported by Fusion++ is here: [ArgumentOutOfRangeException.txt](https://github.com/awaescher/Fusion/files/4556875/ArgumentOutOfRangeException.txt)

And the actual logs in question are here: [2020.04.30.07.37.37.5091.zip](https://github.com/awaescher/Fusion/files/4556873/2020.04.30.07.37.37.5091.zip)

I'm not sure whether this might be related to issue #15. In case it's relevant though, the system-time at which I recorded those logs was 5:37pm in AEST (UTC+10).

**Comment by lethek** [comment]
So far it's happening consistently for me with this 'test' web-app (regardless whether Fusion++ records the logs, or the logs are imported in from FUSLOGVW): 
[FusionWebTest-Src.zip](https://github.com/awaescher/Fusion/files/4556948/FusionWebTest-Src.zip)

However, it appears to be working fine with a much larger, real web-app I'm working on.

**Comment by awaescher** [comment]
I could reproduce this with the first zip file you attached, thanks for the repro.

**Comment by awaescher** [comment]
[Version 1.3](https://github.com/awaescher/Fusion/releases/tag/v1.3) was just released.
I would be happy to hear if this issue is gone now.
